services:
  test:
    image: homeassistant/home-assistant:2025.11
    container_name: oura-test
    volumes:
      - ./custom_components:/config/custom_components
      - ./tests:/config/tests
      - ./requirements_test.txt:/config/requirements_test.txt
      - ./pytest.ini:/config/pytest.ini
    working_dir: /config
    command: sh -c "pip install -r requirements_test.txt && python -m pytest tests/ -v"
    environment:
      - PYTHONPATH=/config
